name = "urbancarry-custom-app"
client_id = "YOUR_CLIENT_ID"
application_url = "YOUR_APP_URL"
embedded = true

[access_scopes]
# Read and modify products, including product listings
scopes = "write_products,read_products,write_inventory,read_inventory,write_orders,read_orders"

[auth]
redirect_urls = [
  "https://YOUR_APP_URL/auth/callback",
  "https://YOUR_APP_URL/auth/shopify/callback",
  "https://YOUR_APP_URL/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false